name: 🚀 Deploy on production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: 🔨 build production
        #uses: lemonarc/jekyll-action@1.0.0
        run: |
          bundle config path vendor/bundle
          bundle install
          bundle exec jekyll build
          cp -f .htaccess _site/

      - name: 🔐 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: 🎯 Adding Known Hosts
        run: ssh-keyscan -H agilebrazil.com >> ~/.ssh/known_hosts
      
      - name: 🚀 deploy on production
        run: rsync -zav --progress --delete -e 'ssh -o StrictHostKeyChecking=no' _site/ agilebrazil@agilebrazil.com:agilebrazil.com/2024